# src: ./.github/actions/create-pr-from-worktree/action.yml
# @(#) : Composite action to create PRs from worktree with auto-merge enabled
#
# Copyright (c) 2025 atsushifx <https://github.com/atsushifx>
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

name: Create PR from Worktree
description: Create or update a Pull Request from worktree with labels and auto-merge enabled (assumes branches already exist and are pushed)
author: atsushifx

inputs:
  pr-branch:
    description: "PR branch name"
    required: true
  pr-title:
    description: "Pull request title"
    required: true
  pr-body:
    description: "Pull request body/description"
    required: true
  labels:
    description: "Comma-separated list of labels to add"
    required: false
    default: ""
  merge-method:
    description: "Auto-merge method (merge, squash, rebase, never). Use 'never' to disable auto-merge."
    required: false
    default: "squash"

outputs:
  validation-status:
    description: "Overall validation status (ok, fail, error, warning)"
    value: ${{ steps.validate-branches.outputs.status }}
  validation-message:
    description: "Validation status message (if any)"
    value: ${{ steps.validate-branches.outputs.message }}
  pr-number:
    description: "Created/updated PR number (empty if validation failed)"
    value: ${{ steps.create-pr.outputs.pr-number }}
  pr-url:
    description: "Pull request URL (empty if validation failed)"
    value: ${{ steps.create-pr.outputs.pr-url }}
  pr-operation:
    description: "Operation performed (created, updated, update-failed, or empty if validation failed)"
    value: ${{ steps.create-pr.outputs.operation }}
  automerge-status:
    description: "Auto-merge status (enabled, failed, timeout, or skipped if merge-method=never)"
    value: ${{ steps.enable-automerge.outputs.automerge-status }}

runs:
  using: composite
  steps:
    #    - name: Validate runner environment
    #      id: validate-environment
    #      uses: aglabo/.github/.github/actions/validate-environment@r1.2.0
    #      with:
    #        additional-apps: "gh|gh|regex:version ([0-9.]+)|2.0"
    - name: Detect base branch
      id: detect
      shell: bash
      run: |
        # Get current branch as base branch
        BASE_BRANCH=$(git symbolic-ref --short HEAD)

        if [ -z "$BASE_BRANCH" ]; then
          echo "::error::Failed to detect base branch (current branch)"
          echo "::error::Ensure action is run on a checked-out branch (not detached HEAD)"
          exit 1
        fi

        echo "Detected base branch (current): $BASE_BRANCH"
        echo "base-branch=$BASE_BRANCH" >> $GITHUB_OUTPUT
        echo "status=ok" >> $GITHUB_OUTPUT

    - name: Validate API rate limit
      id: validate-ratelimit
      if: steps.detect.outcome == 'success'
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: bash ${{ github.action_path }}/scripts/validate-ratelimit.sh

    - name: Validate branches
      id: validate-branches
      if: |
        steps.detect.outcome == 'success' &&
        steps.validate-ratelimit.outputs.status == 'ok'
      shell: bash
      run: |
        bash ${{ github.action_path }}/scripts/validate-branches.sh \
          "${{ steps.detect.outputs.base-branch }}" \
          "${{ inputs.pr-branch }}"

    - name: Create or update Pull Request
      id: create-pr
      if: |
        steps.detect.outcome == 'success' &&
        steps.validate-ratelimit.outputs.status == 'ok' &&
        steps.validate-branches.outputs.status == 'ok'
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        bash ${{ github.action_path }}/scripts/create-pr.sh \
          "${{ steps.detect.outputs.base-branch }}" \
          "${{ inputs.pr-branch }}" \
          "${{ inputs.pr-title }}" \
          "${{ inputs.pr-body }}"

    - name: Validate create-pr ABI contract
      if: steps.create-pr.outcome == 'success'
      shell: bash
      run: |
        # ABI CONTRACT ENFORCEMENT: create-pr.sh MUST output pr-number, pr-url, operation
        # This is a boundary check - fail immediately if contract is violated

        PR_NUMBER="${{ steps.create-pr.outputs.pr-number }}"
        PR_URL="${{ steps.create-pr.outputs.pr-url }}"
        OPERATION="${{ steps.create-pr.outputs.operation }}"

        if [ -z "$PR_NUMBER" ]; then
          echo "::error::ABI contract violation: create-pr.sh did not set pr-number output"
          echo "::error::This indicates a bug in create-pr.sh implementation"
          exit 1
        fi

        if [ -z "$PR_URL" ]; then
          echo "::error::ABI contract violation: create-pr.sh did not set pr-url output"
          echo "::error::This indicates a bug in create-pr.sh implementation"
          exit 1
        fi

        if [ -z "$OPERATION" ]; then
          echo "::error::ABI contract violation: create-pr.sh did not set operation output"
          echo "::error::This indicates a bug in create-pr.sh implementation"
          exit 1
        fi

        # Validate operation is one of the expected values
        case "$OPERATION" in
          created|updated|update-failed) ;;
          *)
            echo "::error::ABI contract violation: invalid operation value: $OPERATION"
            echo "::error::Expected: created, updated, or update-failed"
            exit 1
            ;;
        esac

        echo "✓ ABI contract validated: pr-number=$PR_NUMBER, operation=$OPERATION"

    - name: Set PR labels
      id: set-labels
      if: |
        steps.detect.outcome == 'success' &&
        steps.validate-ratelimit.outputs.status == 'ok' &&
        steps.validate-branches.outputs.status == 'ok' &&
        inputs.labels != ''
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        PR_NUMBER="${{ steps.create-pr.outputs.pr-number }}"
        LABELS="${{ inputs.labels }}"

        # Get existing labels in the repository
        echo "Checking existing labels in repository..."
        EXISTING_LABELS=$(timeout 30s gh label list --json name --jq '.[].name' 2>&1 || echo "")

        # Split labels by comma and process each one
        IFS=',' read -ra LABEL_ARRAY <<< "$LABELS"
        LABELS_TO_ADD=""
        LABELS_CREATED=0
        LABELS_SKIPPED=0

        for label in "${LABEL_ARRAY[@]}"; do
          # Trim whitespace
          label=$(echo "$label" | xargs)

          # Check if label already exists
          if echo "$EXISTING_LABELS" | grep -Fxq "$label"; then
            echo "  Label '$label' already exists"
            LABELS_TO_ADD="${LABELS_TO_ADD}${label},"
          else
            # Try to create label (may fail due to permissions)
            echo "  Creating label '$label'..."
            if timeout 30s gh label create "$label" --force 2>&1; then
              echo "  ✓ Label '$label' created"
              LABELS_CREATED=$((LABELS_CREATED + 1))
              LABELS_TO_ADD="${LABELS_TO_ADD}${label},"
            else
              EXIT_CODE=$?
              if [ $EXIT_CODE -eq 124 ]; then
                echo "  ::warning::Timeout creating label '$label' (skipped)"
              else
                echo "  ::warning::Failed to create label '$label' (insufficient permissions or other error)"
                echo "  ::warning::This label will be skipped. Ensure 'contents: write' permission is granted."
              fi
              LABELS_SKIPPED=$((LABELS_SKIPPED + 1))
            fi
          fi
        done

        # Remove trailing comma
        LABELS_TO_ADD="${LABELS_TO_ADD%,}"

        # Add labels to PR if any are available
        if [ -n "$LABELS_TO_ADD" ]; then
          echo "Adding labels to PR: $LABELS_TO_ADD"
          if timeout 60s gh pr edit "$PR_NUMBER" --add-label "$LABELS_TO_ADD" 2>&1; then
            echo "✓ Added labels to PR: $LABELS_TO_ADD"
            if [ $LABELS_CREATED -gt 0 ]; then
              echo "  ($LABELS_CREATED label(s) created)"
            fi
            if [ $LABELS_SKIPPED -gt 0 ]; then
              echo "  ::warning::$LABELS_SKIPPED label(s) were skipped due to creation failures"
            fi
          else
            EXIT_CODE=$?
            if [ $EXIT_CODE -eq 124 ]; then
              echo "::warning::GitHub API call (gh pr edit) timed out after 60 seconds"
            else
              echo "::warning::Failed to add labels to PR (this does not affect PR creation)"
            fi
          fi
        else
          echo "::warning::No labels could be added (all label creations failed)"
          echo "::warning::Ensure 'contents: write' permission is granted to create labels"
        fi

    - name: Validate merge-method input
      if: |
        steps.detect.outcome == 'success' &&
        steps.validate-ratelimit.outputs.status == 'ok' &&
        steps.validate-branches.outputs.status == 'ok'
      shell: bash
      run: |
        # INPUT VALIDATION: merge-method must be one of the whitelisted values
        # This prevents typos from being silently converted to API errors
        MERGE_METHOD="${{ inputs.merge-method }}"

        case "$MERGE_METHOD" in
          merge|squash|rebase|never)
            echo "✓ Valid merge-method: $MERGE_METHOD"
            ;;
          *)
            echo "::error::Invalid merge-method: $MERGE_METHOD"
            echo "::error::Allowed values: merge, squash, rebase, never"
            exit 1
            ;;
        esac

    - name: Enable auto-merge
      id: enable-automerge
      if: |
        steps.detect.outcome == 'success' &&
        steps.validate-ratelimit.outputs.status == 'ok' &&
        steps.validate-branches.outputs.status == 'ok' &&
        inputs.merge-method != 'never'
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        PR_NUMBER="${{ steps.create-pr.outputs.pr-number }}"

        # Enable auto-merge with specified method
        # Timeout after 60 seconds
        # NOTE: Auto-merge failure is treated as warning, not error
        # PR creation has already succeeded at this point
        if ! timeout 60s gh pr merge "$PR_NUMBER" --auto --${{ inputs.merge-method }} 2>&1; then
          EXIT_CODE=$?
          if [ $EXIT_CODE -eq 124 ]; then
            echo "::warning::GitHub API call (gh pr merge) timed out after 60 seconds"
            echo "automerge-status=timeout" >> "$GITHUB_OUTPUT"
          else
            echo "::warning::Failed to enable auto-merge (check repository settings and permissions)"
            echo "automerge-status=failed" >> "$GITHUB_OUTPUT"
          fi
          exit 0  # Do not fail the action - PR was created successfully
        fi

        echo "✓ Enabled auto-merge (${{ inputs.merge-method }})"
        echo "automerge-status=enabled" >> "$GITHUB_OUTPUT"
        echo "Note: PR will auto-merge once all required checks pass and approvals are received"

    - name: Validate action outputs (final sanity check)
      if: always()
      shell: bash
      run: |
        # FINAL SANITY CHECK: Validate that outputs are consistent with validation status
        # Note: This is a post-execution diagnostic, not a boundary check
        # Boundary checks happen immediately after each critical step (see ABI contract validation)

        VALIDATION_STATUS="${{ steps.validate-branches.outputs.status }}"
        PR_NUMBER="${{ steps.create-pr.outputs.pr-number }}"

        # If validation passed but PR was not created, this is an internal error
        if [ "$VALIDATION_STATUS" = "ok" ] && [ -z "$PR_NUMBER" ]; then
          echo "::error::Internal error: Validation passed but PR was not created"
          echo "::error::This indicates a bug in the action logic"
          echo "::error::(This should have been caught by ABI contract validation)"
          exit 1
        fi

        # If validation failed, PR number should be empty (expected)
        if [ "$VALIDATION_STATUS" != "ok" ] && [ -n "$PR_NUMBER" ]; then
          echo "::warning::Unexpected state: Validation failed but PR number is set"
        fi

        echo "✓ Final sanity check passed"
