# src: ./.github/actions/pr-worktree-cleanup/action.yml
# @(#) : Composite action to clean up worktree created by pr-worktree-initialize
#
# Copyright (c) 2026- aglabo <https://github.com/aglabo>
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

name: PR Worktree Cleanup
description: Remove a git worktree created by pr-worktree-initialize
author: atsushifx

inputs:
  worktree-dir:
    description: "Directory path of the worktree to remove (optional, auto-detected if not provided)"
    required: false
  base-branch:
    description: "Base branch to exclude from cleanup (optional, auto-detected if not provided)"
    required: false
  force:
    description: "Force removal even if worktree has uncommitted changes"
    required: false
    default: "false"

outputs:
  status:
    description: "Status of cleanup operation (success, skipped, error)"
    value: ${{ steps.get_worktree.outputs.status || steps.validate_worktree.outputs.status || steps.cleanup_worktree.outputs.status }}
  message:
    description: "Detailed message about the cleanup operation"
    value: ${{ steps.get_worktree.outputs.message || steps.validate_worktree.outputs.message || steps.cleanup_worktree.outputs.message }}
  removed-path:
    description: "Path of the removed worktree"
    value: ${{ steps.get_worktree.outputs.worktree-path }}

runs:
  using: composite
  steps:
    - name: Get worktree path
      id: get_worktree
      shell: bash
      run: |
        WORKTREE_PATH=""
        STATUS=""
        MESSAGE=""

        if [ -n "${{ inputs.worktree-dir }}" ]; then
          # Use provided worktree-dir
          WORKTREE_PATH="${{ inputs.worktree-dir }}"
          echo "Using provided worktree path: ${WORKTREE_PATH}"
        else
          # Auto-detect worktree: First count, then decide
          if [ -n "${{ inputs.base-branch }}" ]; then
            BASE_BRANCH="${{ inputs.base-branch }}"
          else
            BASE_BRANCH=$(git symbolic-ref --short HEAD)
          fi

          echo "Auto-detecting worktree (excluding base branch: ${BASE_BRANCH})"

          # Get list of worktrees excluding base branch
          WORKTREE_LIST=$(
            git worktree list --porcelain |
              awk -v base="${BASE_BRANCH}" '
                /^worktree / { path=$2 }
                /^branch / {
                  gsub("refs/heads/", "", $2)
                  if ($2 != base) print path
                }
                '
            )

          # Count worktrees first
          if [ -z "${WORKTREE_LIST}" ]; then
            WORKTREE_COUNT=0
          else
            WORKTREE_COUNT=$(echo "${WORKTREE_LIST}" | wc -l)
          fi

          echo "Found ${WORKTREE_COUNT} worktree(s) excluding base branch"

          # Decide: continue or skip based on count
          if [ "${WORKTREE_COUNT}" -eq 0 ]; then
            echo "::notice::No worktrees found to clean up (excluding base branch: ${BASE_BRANCH})"
            STATUS="skipped"
            MESSAGE="No worktrees found to clean up (excluding base branch: ${BASE_BRANCH})"
          elif [ "${WORKTREE_COUNT}" -gt 1 ]; then
            echo "::notice::Multiple worktrees found (${WORKTREE_COUNT}), skipping auto-detection. Please specify worktree-dir explicitly."
            echo "Available worktrees:"
            echo "${WORKTREE_LIST}"
            STATUS="skipped"
            MESSAGE="Multiple worktrees found (${WORKTREE_COUNT}), specify worktree-dir explicitly"
          else
            # Exactly 1 worktree: continue with cleanup
            WORKTREE_PATH="${WORKTREE_LIST}"
            echo "Found worktree at: ${WORKTREE_PATH}"
          fi
        fi

        echo "worktree-path=${WORKTREE_PATH}" >> $GITHUB_OUTPUT
        echo "status=${STATUS}" >> $GITHUB_OUTPUT
        echo "message=${MESSAGE}" >> $GITHUB_OUTPUT

    - name: Validate worktree
      id: validate_worktree
      if: steps.get_worktree.outputs.status != 'skipped'
      shell: bash
      run: |
        WORKTREE_PATH="${{ steps.get_worktree.outputs.worktree-path }}"

        # Check if worktree path is provided
        if [ -z "${WORKTREE_PATH}" ]; then
          echo "status=skipped" >> $GITHUB_OUTPUT
          echo "message=No worktree path specified" >> $GITHUB_OUTPUT
          exit 0
        fi

        # Check if directory exists
        if [ ! -d "${WORKTREE_PATH}" ]; then
          echo "status=error" >> $GITHUB_OUTPUT
          echo "message=Worktree directory does not exist: ${WORKTREE_PATH}" >> $GITHUB_OUTPUT
          echo "::error::Worktree directory does not exist: ${WORKTREE_PATH}"
          exit 0
        fi

        # Validate it's a git worktree (check for .git file)
        if [ ! -e "${WORKTREE_PATH}/.git" ]; then
          echo "status=error" >> $GITHUB_OUTPUT
          echo "message=Directory is not a valid git worktree: ${WORKTREE_PATH}" >> $GITHUB_OUTPUT
          echo "::error::Directory is not a valid git worktree: ${WORKTREE_PATH}"
          exit 0
        fi

        # Check for uncommitted changes if force=false
        if [ "${{ inputs.force }}" = "false" ]; then
          if [ -n "$(git -C "${WORKTREE_PATH}" status --porcelain)" ]; then
            echo "status=error" >> $GITHUB_OUTPUT
            echo "message=Cannot remove worktree with uncommitted changes (force=false): ${WORKTREE_PATH}" >> $GITHUB_OUTPUT
            echo "::error::Cannot remove worktree with uncommitted changes. Set force=true to override: ${WORKTREE_PATH}"
            exit 0
          fi
        fi

        echo "Validation passed for worktree: ${WORKTREE_PATH}"

    - name: Cleanup worktree
      id: cleanup_worktree
      if: steps.validate_worktree.result == 'success' && steps.get_worktree.outputs.status != 'skipped' && steps.validate_worktree.outputs.status != 'skipped' && steps.validate_worktree.outputs.status != 'error'
      shell: bash
      run: |
        WORKTREE_PATH="${{ steps.get_worktree.outputs.worktree-path }}"

        echo "Removing worktree at: ${WORKTREE_PATH}"

        # Build remove command with force flag if needed
        FORCE_FLAG=""
        if [ "${{ inputs.force }}" = "true" ]; then
          FORCE_FLAG="--force"
        fi

        # Execute removal
        if git worktree remove ${FORCE_FLAG} "${WORKTREE_PATH}"; then
          echo "status=success" >> $GITHUB_OUTPUT
          echo "message=Worktree removed successfully: ${WORKTREE_PATH}" >> $GITHUB_OUTPUT
          echo "✓ Removed worktree at: ${WORKTREE_PATH}"
        else
          echo "status=error" >> $GITHUB_OUTPUT
          echo "message=Failed to remove worktree: ${WORKTREE_PATH}" >> $GITHUB_OUTPUT
          echo "::error::Failed to remove worktree at: ${WORKTREE_PATH}"
          exit 1
        fi

        exit 0

    - name: Output cleanup results
      if: always()
      shell: bash
      run: |
        STATUS="${{ steps.get_worktree.outputs.status || steps.validate_worktree.outputs.status || steps.cleanup_worktree.outputs.status }}"
        MESSAGE="${{ steps.get_worktree.outputs.message || steps.validate_worktree.outputs.message || steps.cleanup_worktree.outputs.message }}"
        WORKTREE_PATH="${{ steps.get_worktree.outputs.worktree-path }}"

        echo ""
        echo "=== Worktree Cleanup Complete ==="
        echo "Status: ${STATUS}"

        if [ -n "${MESSAGE}" ]; then
          echo "Message: ${MESSAGE}"
        fi

        if [ "${STATUS}" = "success" ] && [ -n "${WORKTREE_PATH}" ]; then
          echo "Removed Path: ${WORKTREE_PATH}"
        fi
        echo ""
