# src: ./.github/actions/validate-environment/action.yml
# @(#) : composite GitHub Action to validate runner environment
#
# Copyright (c) 2026- aglabo <https://github.com/aglabo>
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

name: "Validate Environment"
description: |
  Validate GitHub Actions runner environment.
  REQUIREMENTS: Linux only, GitHub-hosted runners only (ubuntu-latest, ubuntu-22.04, etc.)
  NOT SUPPORTED: Windows, macOS, self-hosted runners
  (Note: ARM64 validated on Linux if GitHub provides ARM64 runners)
  Validates: OS/architecture, Git, curl, optional applications
  Special: gh CLI validation includes authentication check (gh auth status)
author: "aglabo"

branding:
  icon: "check-circle"
  color: "green"

# =============================================================================
# Internal ABI Requirements (enforced by validate-git-runner.sh):
# - Linux runner (uname -s = linux)
# - bash shell (composite action requirement)
# - GNU coreutils: sort -V (used by validate-apps.sh version comparison)
# - Standard commands: uname, tr, cut, sed, grep
# - validate-git-runner.sh enforces OS/architecture/runner constraints
#
# Security Model (default: Git, curl only):
# - Does NOT require GITHUB_TOKEN
# - Does NOT access secrets
# - Does NOT require special permissions
# - Safe for use in any workflow without security implications
#
# When gh CLI is added (via additional-apps):
# - gh authentication check requires GITHUB_TOKEN or prior 'gh auth login'
# - Workflows should ensure GITHUB_TOKEN is available
#   (GitHub Actions provides this by default in 'github.token' context)
# =============================================================================

inputs:
  architecture:
    description: >
      Expected runner architecture (canonical format): 'amd64' or 'arm64'.
      Script normalizes uname -m output (x86_64→amd64, aarch64→arm64).

      **ABI Contract:** Passed to validate-git-runner.sh as EXPECTED_ARCHITECTURE environment variable.
    required: false
    default: "amd64"
  additional-apps:
    description: |
      Additional applications to validate beyond default (Git, curl).
      Format: Newline-separated list of pipe-delimited (|) definitions.
      Each definition: cmd|app_name|version_extractor|min_version

      version_extractor types (prefix-typed, safe sed-only):
        - field:N = Extract Nth field (space-delimited) from --version output
        - regex:PATTERN = sed -E with capture group \1 (use # as delimiter internally)
        - (empty) = Auto-extract semver (X.Y or X.Y.Z pattern)

      min_version: Minimum required version (empty = skip check, show warning)

      Single app: "gh|gh|regex:version ([0-9.]+)|2.0"
      Multiple apps (use YAML multiline string):
        additional-apps: |
          gh|gh|regex:version ([0-9.]+)|2.0
          node|Node.js|regex:v([0-9.]+)|18.0

      Note: gh CLI validation includes authentication check via 'gh auth status'
      Security: NO eval usage, sed-only extraction, prefix-typed extractors prevent injection

      **ABI Contract:** Passed as positional arguments to validate-apps.sh.
    required: false
    default: ""

outputs:
  runner-status:
    description: >
      OS validation status ('success' or 'error').
      Always set by validate-git-runner.sh.
    value: ${{ steps.validate-runner.outputs.status }}
  runner-message:
    description: >
      OS validation message.
      Always set by validate-git-runner.sh.
    value: ${{ steps.validate-runner.outputs.message }}
  apps-status:
    description: >
      Applications validation status ('success' or 'error').
      Always set by validate-apps.sh.
    value: ${{ steps.validate-apps.outputs.status }}
  apps-message:
    description: >
      Applications validation message.
      Always set by validate-apps.sh.
    value: ${{ steps.validate-apps.outputs.message }}
  validated-apps:
    description: >
      Comma-separated list of validated application names.
      **Output Contract:** Only set when apps-status='success'. Undefined on error.
    value: ${{ steps.validate-apps.outputs.validated_apps }}
  validated-count:
    description: >
      Number of successfully validated applications.
      **Output Contract:** Only set when apps-status='success'. Undefined on error.
    value: ${{ steps.validate-apps.outputs.validated_count }}
  failed-apps:
    description: >
      Comma-separated list of failed application names (empty if all passed).
      **Output Contract:** Only set when apps-status='error'. Undefined on success.
    value: ${{ steps.validate-apps.outputs.failed_apps }}
  failed-count:
    description: >
      Number of failed applications (0 if all passed).
      **Output Contract:** Only set when apps-status='error'. Undefined on success.
    value: ${{ steps.validate-apps.outputs.failed_count }}

runs:
  using: "composite"
  steps:
    # Output Mechanism:
    # 1. Scripts write to $GITHUB_OUTPUT (key=value format)
    # 2. Outputs automatically available as steps.<step-id>.outputs.<key>
    # 3. Top-level outputs: section references step outputs for external access
    - name: "Validate OS and environment variables"
      id: validate-runner
      shell: bash
      env:
        EXPECTED_ARCHITECTURE: ${{ inputs.architecture }}
      run: |
        set -euo pipefail
        bash "${GITHUB_ACTION_PATH}/scripts/validate-git-runner.sh"
      # Outputs: status, message (written to $GITHUB_OUTPUT by script)

    - name: "Validate required applications"
      id: validate-apps
      shell: bash
      env:
        ADDITIONAL_APPS: ${{ inputs.additional-apps }}
      run: |
        set -euo pipefail
        if [ -n "${ADDITIONAL_APPS}" ]; then
          # Parse newline-separated app definitions into array
          # Each definition format: cmd|app_name|version_extractor|min_version
          # Filter out empty lines and pass as separate arguments
          readarray -t app_defs < <(echo "${ADDITIONAL_APPS}" | grep -v '^[[:space:]]*$')
          bash "${GITHUB_ACTION_PATH}/scripts/validate-apps.sh" "${app_defs[@]}"
        else
          bash "${GITHUB_ACTION_PATH}/scripts/validate-apps.sh"
        fi
      # Outputs: status, message, validated_apps, validated_count, failed_apps, failed_count
