# src: ./.github/actions/pr-worktree-setup/action.yml
# @(#) : create git worktree and setup gitsign for signed commits
#
# Copyright (c) 2026- aglabo <https://github.com/aglabo>
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

name: PR Worktree Setup
description: Create a git worktree and configure gitsign for keyless signed commits using Sigstore
author: atsushifx

inputs:
  branch-name:
    description: "Branch name for the worktree"
    required: true
  worktree-dir:
    description: "Directory path for the worktree"
    required: true
  gitsign-version:
    description: "Gitsign version to install (e.g., v0.14.0)"
    required: false
    default: "v0.14.0"
  user-name:
    description: "Git user name for commits"
    required: false
    default: "github-actions[bot]"
  user-email:
    description: "Git user email for commits"
    required: false
    default: "github-actions[bot]@users.noreply.github.com"

outputs:
  worktree-path:
    description: "Absolute path to the created worktree"
    value: ${{ steps.create_worktree.outputs.worktree_path }}
  status:
    description: "Overall setup status (success, error, warning)"
    value: ${{ steps.set_final_status.outputs.status }}
  message:
    description: "Status message with detailed information"
    value: ${{ steps.set_final_status.outputs.message }}

runs:
  using: composite
  steps:
    - name: Install gitsign
      id: install_gitsign
      shell: bash
      env:
        VERSION: ${{ inputs.gitsign-version }}
      run: |
        OUTPUT=$(bash ${{ github.action_path }}/scripts/install-gitsign.sh ${{inputs.gitsign-version }} 2>&1)
        echo "$OUTPUT"

        # Extract status and path from script output
        STATUS_LINE=$(echo "$OUTPUT" | grep "^EXIT_STATUS=" | head -1)
        PATH_LINE=$(echo "$OUTPUT" | grep "^GITSIGN_PATH=" | head -1)

        # Parse status
        STATUS=$(echo "$STATUS_LINE" | cut -d= -f2 | cut -d: -f1)
        MESSAGE=$(echo "$STATUS_LINE" | cut -d= -f2 | cut -d: -f2-)

        # Parse gitsign path
        GITSIGN_PATH=$(echo "$PATH_LINE" | cut -d= -f2)

        # Set outputs
        echo "status=$STATUS" >> $GITHUB_OUTPUT
        echo "message=$MESSAGE" >> $GITHUB_OUTPUT
        echo "gitsign_path=$GITSIGN_PATH" >> $GITHUB_OUTPUT

        # Log error if installation failed (but don't exit 1)
        if [ "$STATUS" = "error" ]; then
          echo "::error::Gitsign installation failed: $MESSAGE"
        fi

    - name: Validate gitsign installation
      id: validate_gitsign
      shell: bash
      run: |
        OUTPUT=$(bash ${{ github.action_path }}/scripts/validate-gitsign.sh)
        echo "$OUTPUT"

        # Extract EXIT_STATUS line
        STATUS_LINE=$(echo "$OUTPUT" | grep "^EXIT_STATUS=" | head -1)

        # Extract status (ok|error|warning)
        STATUS=$(echo "$STATUS_LINE" | cut -d= -f2 | cut -d: -f1)
        echo "status=$STATUS" >> $GITHUB_OUTPUT

        # Extract message
        MESSAGE=$(echo "$STATUS_LINE" | cut -d= -f2 | cut -d: -f2-)
        echo "message=$MESSAGE" >> $GITHUB_OUTPUT

        # Log error if validation failed (but don't exit 1)
        if [ "$STATUS" = "error" ]; then
          echo "::error::Gitsign validation failed: $MESSAGE"
        fi

    - name: Validate worktree directory
      id: validate_directory
      if: steps.validate_gitsign.outputs.status != 'error'
      shell: bash
      run: |
        WORKTREE_DIR="${{ inputs.worktree-dir }}"

        # Check if directory already exists
        if [ -e "${WORKTREE_DIR}" ]; then
          echo "::error::Directory already exists: ${WORKTREE_DIR}"
          echo "::error::Cannot create worktree at existing location"
          echo "::error::Please remove the directory first or choose a different path"
          echo "status=error" >> $GITHUB_OUTPUT
          echo "message=Directory already exists: ${WORKTREE_DIR}" >> $GITHUB_OUTPUT
          exit 0
        fi

        # Try to create directory (validates parent directory exists and is writable)
        if ! mkdir -p "${WORKTREE_DIR}"; then
          echo "::error::Failed to create directory: ${WORKTREE_DIR}"
          echo "::error::Check parent directory permissions or path validity"
          echo "status=error" >> $GITHUB_OUTPUT
          echo "message=Failed to create directory: ${WORKTREE_DIR}" >> $GITHUB_OUTPUT
          exit 0
        fi

        # Remove the directory (git worktree add will create it)
        rmdir "${WORKTREE_DIR}"

        echo "status=ok" >> $GITHUB_OUTPUT
        echo "message=Directory validation passed" >> $GITHUB_OUTPUT
        echo "✓ Worktree directory validation passed"

    - name: Create worktree
      id: create_worktree
      if: steps.validate_gitsign.outputs.status != 'error' && steps.validate_directory.outputs.status == 'ok'
      shell: bash
      run: |
        WORKTREE_DIR="${{ inputs.worktree-dir }}"
        BRANCH_NAME="${{ inputs.branch-name }}"

        echo "Creating worktree at: ${WORKTREE_DIR}"
        echo "Branch: ${BRANCH_NAME}"

        # Check if branch already exists
        if git show-ref --verify --quiet "refs/heads/${BRANCH_NAME}"; then
          echo "::error::Branch already exists: ${BRANCH_NAME}"
          echo "::error::Cannot create worktree with -B flag as it would force-reset the existing branch"
          echo "::error::Please use a different branch name or delete the existing branch first"
          echo "status=failed" >> $GITHUB_OUTPUT
          echo "message=Branch already exists: ${BRANCH_NAME}" >> $GITHUB_OUTPUT
          exit 0
        fi

        # Create worktree with branch
        if ! git worktree add -B "${BRANCH_NAME}" "${WORKTREE_DIR}"; then
          echo "::error::Failed to create worktree"
          echo "status=failed" >> $GITHUB_OUTPUT
          echo "message=Failed to create worktree at ${WORKTREE_DIR}" >> $GITHUB_OUTPUT
          exit 0
        fi

        # Get absolute path
        WORKTREE_PATH=$(cd "${WORKTREE_DIR}" && pwd)
        echo "worktree_path=${WORKTREE_PATH}" >> $GITHUB_OUTPUT
        echo "status=success" >> $GITHUB_OUTPUT
        echo "message=Worktree created successfully" >> $GITHUB_OUTPUT
        echo "✓ Worktree created at: ${WORKTREE_PATH}"

    - name: Configure gitsign in worktree
      id: configure_gitsign
      if: steps.create_worktree.outputs.status == 'success' && steps.validate_gitsign.outputs.status != 'error'
      shell: bash
      run: |
        cd "${{ steps.create_worktree.outputs.worktree_path }}"

        echo "Configuring gitsign for signed commits..."

        # Configure git to use gitsign
        git config --local commit.gpgsign true
        git config --local gpg.format x509
        git config --local gpg.x509.program "${{ steps.install_gitsign.outputs.gitsign_path }}"

        echo "✓ Gitsign configured"

        # Display configuration
        echo ""
        echo "Git signing configuration:"
        git config --local --get-regexp 'commit\.gpgsign|gpg\.'

    - name: Set git user configuration
      id: configure_user
      if: steps.create_worktree.outputs.status == 'success' && steps.validate_gitsign.outputs.status != 'error'
      shell: bash
      run: |
        cd "${{ steps.create_worktree.outputs.worktree_path }}"

        echo "Setting git user configuration..."

        # Set user name and email
        git config --local user.name "${{ inputs.user-name }}"
        git config --local user.email "${{ inputs.user-email }}"

        echo "✓ User configuration set"
        echo "  Name:  ${{ inputs.user-name }}"
        echo "  Email: ${{ inputs.user-email }}"

    - name: Set final status
      id: set_final_status
      shell: bash
      run: |
        # Collect status from all validation steps
        GITSIGN_STATUS="${{ steps.validate_gitsign.outputs.status }}"
        GITSIGN_MESSAGE="${{ steps.validate_gitsign.outputs.message }}"
        DIRECTORY_STATUS="${{ steps.validate_directory.outputs.status }}"
        DIRECTORY_MESSAGE="${{ steps.validate_directory.outputs.message }}"
        WORKTREE_STATUS="${{ steps.create_worktree.outputs.status }}"
        WORKTREE_MESSAGE="${{ steps.create_worktree.outputs.message }}"

        # Default to success if all steps completed
        FINAL_STATUS="success"
        FINAL_MESSAGE="Worktree setup completed successfully"

        # Check for failures (priority: error > failed > warning > success)
        if [ "$GITSIGN_STATUS" = "error" ]; then
          FINAL_STATUS="failed"
          FINAL_MESSAGE="Setup failed: $GITSIGN_MESSAGE"
        elif [ "$DIRECTORY_STATUS" = "error" ]; then
          FINAL_STATUS="failed"
          FINAL_MESSAGE="Setup failed: $DIRECTORY_MESSAGE"
        elif [ -z "$WORKTREE_STATUS" ]; then
          # Worktree creation was skipped (due to validation errors)
          FINAL_STATUS="skipped"
          FINAL_MESSAGE="Worktree creation skipped due to validation errors"
        elif [ "$WORKTREE_STATUS" = "failed" ]; then
          FINAL_STATUS="failed"
          FINAL_MESSAGE="$WORKTREE_MESSAGE"
        elif [ "$GITSIGN_STATUS" = "warning" ]; then
          FINAL_STATUS="warning"
          FINAL_MESSAGE="Worktree setup completed with warnings: $GITSIGN_MESSAGE"
        fi

        # Set outputs
        echo "status=$FINAL_STATUS" >> $GITHUB_OUTPUT
        echo "message=$FINAL_MESSAGE" >> $GITHUB_OUTPUT

    - name: Output validation results
      shell: bash
      run: |
        echo ""
        echo "=== Worktree Initialization Complete ==="
        echo "Worktree Path: ${{ steps.create_worktree.outputs.worktree_path }}"
        echo "Branch: ${{ inputs.branch-name }}"
        echo "Gitsign Version: $( gitsign --version | head -1)"
        echo "Setup Status: ${{ steps.set_final_status.outputs.status }}"
        echo "Message: ${{ steps.set_final_status.outputs.message }}"
        echo ""
        echo "Ready for signed commits using Sigstore keyless signing"
