# src: ./.github/actions/pr-worktree-setup/action.yml
# @(#) : create git worktree and setup gitsign for signed commits
#
# Copyright (c) 2026- aglabo <https://github.com/aglabo>
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

name: PR Worktree Setup
description: Create a git worktree and configure gitsign for keyless signed commits using Sigstore
author: atsushifx

inputs:
  branch-name:
    description: "Branch name for the worktree"
    required: true
  worktree-dir:
    description: "Directory path for the worktree"
    required: true
  gitsign-version:
    description: "Gitsign version to install (e.g., v0.14.0)"
    required: false
    default: "v0.14.0"
  user-name:
    description: "Git user name for commits"
    required: false
    default: "github-actions[bot]"
  user-email:
    description: "Git user email for commits"
    required: false
    default: "github-actions[bot]@users.noreply.github.com"

outputs:
  gitsign-path:
    description: "Absolute path to the installed gitsign binary"
    value: ${{ steps.install-gitsign.outputs.gitsign-path }}
  worktree-path:
    description: "Absolute path to the created worktree"
    value: ${{ steps.create-worktree.outputs.worktree-path }}
  status:
    description: "Overall setup status (success, error, warning)"
    value: ${{ steps.set-final-status.outputs.status }}
  message:
    description: "Status message with detailed information"
    value: ${{ steps.set-final-status.outputs.message }}

runs:
  using: composite
  steps:
    - name: Install gitsign
      id: install-gitsign
      shell: bash
      env:
        VERSION: ${{ inputs.gitsign-version }}
      run: |
        bash ${{ github.action_path }}/scripts/install-gitsign.sh ${{inputs.gitsign-version }}

    - name: Validate gitsign installation
      id: validate-gitsign
      if: steps.install-gitsign.outcome == 'success'
      shell: bash
      run: |
        bash ${{ github.action_path }}/scripts/validate-gitsign.sh "${{ steps.install-gitsign.outputs.gitsign-path }}"

    - name: Validate worktree directory
      id: validate-directory
      if: steps.validate-gitsign.outcome == 'success'
      shell: bash
      run: |
        # Add run-id to worktree directory to prevent conflicts during concurrent runs
        BASE_DIR="${{ inputs.worktree-dir }}"
        UNIQUE_SUFFIX="${{ github.run_id }}"
        WORKTREE_DIR="${RUNNER_TEMP}/${BASE_DIR}-${UNIQUE_SUFFIX}"

        echo "Base directory: ${BASE_DIR}"
        echo "Unique suffix: ${UNIQUE_SUFFIX}"
        echo "Final worktree directory: ${WORKTREE_DIR}"

        # Check if directory already exists (should not happen with run-id suffix)
        if [ -e "${WORKTREE_DIR}" ]; then
          echo "::error::Directory already exists: ${WORKTREE_DIR}"
          echo "::error::Cannot create worktree at existing location"
          echo "::error::Please remove the directory first or choose a different path"
          echo "status=error" >> $GITHUB_OUTPUT
          echo "message=Directory already exists: ${WORKTREE_DIR}" >> $GITHUB_OUTPUT
          exit 1
        fi

        # create parent directory
        PARENT_DIR=$(dirname "${WORKTREE_DIR}")
        mkdir -p "${PARENT_DIR}"

        # Validate parent directory exists and is writable
        if [ ! -d "${PARENT_DIR}" ]; then
          echo "::error::Parent directory does not exist: ${PARENT_DIR}"
          echo "::error::Cannot create worktree - parent directory must exist first"
          exit 1
        fi

        if [ ! -w "${PARENT_DIR}" ]; then
          echo "::error::Parent directory is not writable: ${PARENT_DIR}"
          echo "::error::Cannot create worktree - insufficient permissions"
          exit 1
        fi

        echo "✓ Worktree directory validation passed"
        echo "  Target: ${WORKTREE_DIR}"
        echo "  Parent: ${PARENT_DIR} (exists and writable)"

        # Output the final worktree directory for next steps
        echo "worktree-dir=${WORKTREE_DIR}" >> $GITHUB_OUTPUT

    - name: Create worktree
      id: create-worktree
      if: |
        steps.validate-gitsign.outcome == 'success' &&
        steps.validate-directory.outcome == 'success'
      shell: bash
      run: |
        WORKTREE_DIR="${{ steps.validate-directory.outputs.worktree-dir }}"
        BRANCH_NAME="${{ inputs.branch-name }}"

        echo "Creating worktree at: ${WORKTREE_DIR}"
        echo "Branch: ${BRANCH_NAME}"

        # Check if branch already exists locally
        if git show-ref --verify --quiet "refs/heads/${BRANCH_NAME}"; then
          echo "::notice::Local branch already exists: ${BRANCH_NAME}"
          echo "Using existing branch (will update with new changes)"
          BRANCH_EXISTS_LOCALLY=true
        else
          BRANCH_EXISTS_LOCALLY=false
        fi

        # Check if branch already exists on remote
        if git ls-remote --exit-code --heads origin "${BRANCH_NAME}" >/dev/null 2>&1; then
          echo "::notice::Remote branch already exists: ${BRANCH_NAME}"
          echo "Will append new changes to existing branch"
          BRANCH_EXISTS_REMOTELY=true
        else
          BRANCH_EXISTS_REMOTELY=false
        fi

        # Create worktree
        if [ "$BRANCH_EXISTS_LOCALLY" = true ]; then
          # Use existing branch for worktree
          echo "Creating worktree from existing branch..."
          if ! git worktree add "${WORKTREE_DIR}" "${BRANCH_NAME}"; then
            echo "::error::Failed to create worktree from existing branch"
            echo "status=error" >> $GITHUB_OUTPUT
            echo "message=Failed to create worktree at ${WORKTREE_DIR}" >> $GITHUB_OUTPUT
            exit 1
          fi
        else
          # Create new branch for worktree
          echo "Creating worktree with new branch..."
          if ! git worktree add "${WORKTREE_DIR}" -b "${BRANCH_NAME}"; then
            echo "::error::Failed to create worktree"
            echo "status=error" >> $GITHUB_OUTPUT
            echo "message=Failed to create worktree at ${WORKTREE_DIR}" >> $GITHUB_OUTPUT
            exit 1
          fi
        fi

        # Get absolute path
        WORKTREE_PATH=$(cd "${WORKTREE_DIR}" && pwd)
        echo "worktree-path=${WORKTREE_PATH}" >> $GITHUB_OUTPUT
        echo "status=success" >> $GITHUB_OUTPUT
        echo "message=Worktree created successfully" >> $GITHUB_OUTPUT
        echo "✓ Worktree created at: ${WORKTREE_PATH}"

    - name: Configure gitsign in worktree
      id: configure-gitsign
      if: |
        steps.validate-gitsign.outcome == 'success' &&
        steps.create-worktree.outcome == 'success'
      shell: bash
      run: |
        cd "${{ steps.create-worktree.outputs.worktree-path }}"

        echo "Configuring gitsign for signed commits..."

        # Configure git to use gitsign
        git config --local commit.gpgsign true
        git config --local gpg.format x509
        git config --local gpg.x509.program "${{ steps.install-gitsign.outputs.gitsign-path }}"

        echo "✓ Gitsign configured"

        # Display configuration
        echo ""
        echo "Git signing configuration:"
        git config --local --get-regexp 'commit\.gpgsign|gpg\.'

    - name: Set git user configuration
      id: configure-user
      if: |
        steps.validate-gitsign.outcome == 'success' &&
        steps.create-worktree.outcome == 'success'
      shell: bash
      run: |
        cd "${{ steps.create-worktree.outputs.worktree-path }}"

        echo "Setting git user configuration..."

        # Set user name and email
        git config --local user.name "${{ inputs.user-name }}"
        git config --local user.email "${{ inputs.user-email }}"

        echo "✓ User configuration set"
        echo "  Name:  ${{ inputs.user-name }}"
        echo "  Email: ${{ inputs.user-email }}"

    - name: Set final status
      id: set-final-status
      if: always()
      shell: bash
      run: |
        # Collect step outcomes
        INSTALL_OUTCOME="${{ steps.install-gitsign.outcome }}"
        VALIDATE_GITSIGN_OUTCOME="${{ steps.validate-gitsign.outcome }}"
        VALIDATE_DIRECTORY_OUTCOME="${{ steps.validate-directory.outcome }}"
        CREATE_WORKTREE_OUTCOME="${{ steps.create-worktree.outcome }}"
        CONFIGURE_GITSIGN_OUTCOME="${{ steps.configure-gitsign.outcome }}"
        CONFIGURE_USER_OUTCOME="${{ steps.configure-user.outcome }}"

        # Default to success
        FINAL_STATUS="success"
        FINAL_MESSAGE="Worktree setup completed successfully with gitsign configuration"

        # Check for failures (priority: error > skipped > warning > success)
        if [ "$INSTALL_OUTCOME" = "failure" ]; then
          FINAL_STATUS="error"
          FINAL_MESSAGE="Gitsign installation failed"
        elif [ "$VALIDATE_OUTCOME" = "failure" ]; then
          FINAL_STATUS="error"
          FINAL_MESSAGE="Gitsign validation failed (includes output contract check)"
        elif [ "$VALIDATE_GITSIGN_OUTCOME" = "skipped" ]; then
          FINAL_STATUS="skipped"
          FINAL_MESSAGE="Gitsign validation skipped due to installation failure"
        elif [ "$VALIDATE_DIRECTORY_OUTCOME" = "failure" ]; then
          FINAL_STATUS="error"
          FINAL_MESSAGE="Worktree directory validation failed"
        elif [ "$VALIDATE_DIRECTORY_OUTCOME" = "skipped" ]; then
          FINAL_STATUS="skipped"
          FINAL_MESSAGE="Worktree directory validation skipped due to previous failures"
        elif [ "$CREATE_WORKTREE_OUTCOME" = "failure" ]; then
          FINAL_STATUS="error"
          FINAL_MESSAGE="Worktree creation failed"
        elif [ "$WORKTREE_OUTCOME" = "skipped" ]; then
          FINAL_STATUS="skipped"
          FINAL_MESSAGE="Worktree creation skipped due to validation errors"
        elif [ "$CONFIGURE_GITSIGN_OUTCOME" = "failure" ]; then
          FINAL_STATUS="error"
          FINAL_MESSAGE="Gitsign configuration in worktree failed"
        elif [ "$CONFIGURE_GITSIGN_OUTCOME" = "skipped" ]; then
          FINAL_STATUS="skipped"
          FINAL_MESSAGE="Gitsign configuration skipped due to previous failures"
        elif [ "$CONFIGURE_USER_OUTCOME" = "failure" ]; then
          FINAL_STATUS="error"
          FINAL_MESSAGE="Git user configuration failed"
        elif [ "$CONFIGURE_USER_OUTCOME" = "skipped" ]; then
          FINAL_STATUS="skipped"
          FINAL_MESSAGE="Git user configuration skipped due to previous failures"
        fi

        # Set outputs
        echo "status=$FINAL_STATUS" >> $GITHUB_OUTPUT
        echo "message=$FINAL_MESSAGE" >> $GITHUB_OUTPUT

    - name: Output validation results
      if: |
        steps.install-gitsign.outcome == 'success' &&
        steps.create-worktree.outcome == 'success' &&
        steps.configure-gitsign.outcome == 'success'
      shell: bash
      run: |
        echo ""
        echo "=== Worktree Initialization Complete ==="
        echo "Worktree Path: ${{ steps.create-worktree.outputs.worktree-path }}"
        echo "Branch: ${{ inputs.branch-name }}"
        echo "Gitsign Version: $( "${{ steps.install-gitsign.outputs.gitsign-path }}" --version | head -1)"
        echo "Setup Status: ${{ steps.set-final-status.outputs.status }}"
        echo "Message: ${{ steps.set-final-status.outputs.message }}"
        echo ""
        echo "Ready for signed commits using Sigstore keyless signing"
